creation_dt: '2021-04-26T14:00:00Z'
extent:
  center_dt: '2021-04-26T14:00:00Z'
  coord:
    ll: {lon: 1, lat: 1}
    lr: {lon: 3, lat: 1}
    ul: {lon: 1, lat: 2}
    ur: {lon: 3, lat: 2}
  from_dt: '2021-04-26T14:00:00Z'
  to_dt: '2021-04-26T14:00:00Z'
format: {name: NETCDF}
grid_spatial:
  projection:
    geo_ref_points:
      ll: {x: 1, y: 1}
      lr: {x: 3, y: 1}
      ul: {x: 1, y: 2}
      ur: {x: 3, y: 2}
    spatial_reference: EPSG:4326
id: 272302c9-1449-4a33-8166-4b6083a8a713
image:
  bands:
    height: {path: ../minimal-example.nc, layer: height}
    period: {path: ../minimal-example.nc, layer: period}
instrument: {name: NA}
lineage:
  source_datasets: {}
product_type: minimal_example_eo
platform: {code: NA}
